package com.finkid.utils

object Constant {
    const val STUDENTS = "students"
    const val SCHEDULE = "schedule"
    const val TEACHER = "teacher"
    const val NAME = "name"
    const val PHONE = "phone"
    const val WORK = "work"
    const val BIO = "bio"
    const val SERVICES = "services"
    const val IMAGE = "image"
    const val EDUCATION = "education"
    const val THEME = "theme"
    const val DOCUMENT = "document"
    const val ANSWERS = "answers"
    const val ANSWER = "answer"
    const val IS_TRUE = "true"
    const val LESSONS = "lessons"
    const val HOMEWORK = "homework"
    const val USERS = "users"
    const val BIRTH_DATE = "birthDate"
    const val STUDENT = "student"
    const val ROLE = "role"
    const val SUBJECT = "subject"
    const val LESSON = "lesson"
    const val TIME_END = "timeEnd"
    const val TIME_START = "timeStart"
    const val QUESTION = "question"
    const val ANSWER_1 = "answer1"
    const val ANSWER_2 = "answer2"
    const val ANSWER_3 = "answer3"
    const val ANSWER_TRUE = "answerTrue"
}